GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products/
Content-Type: application/json

{
  "name": "Dining Table",
  "price": -170,
  "image_url": "https://secure.img1-fg.wfcdn.com/im/78527195/resize-h800-w800%5Ecompr-r85/4504/45042205/Jambusaria+Vintage+Factory+Coffee+Table.jpg",
  "description": "Iron and wood couch table is a first-rate example of industrial furniture design. An artful blending of metal and reclaimed wood, this industrial design Jambusaria Vintage Factory Cart Coffee Table will be the centerpiece of any room.",
  "supplier_id" : 1
} 

###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "price": -5
} 

###
DELETE http://localhost:3000/products/3


###

GET http://localhost:3000/suppliers

###

GET http://localhost:3000/suppliers/1


###
POST http://localhost:3000/suppliers
Content-Type: application/json

{
  "name" : "Ali Depot",
  "email": "alidepot@info.com",
  "phone_number": "222-333-4444"
}



