GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products/
Content-Type: application/json

{
  "input_name": "TV Stand",
  "input_price": 199,
  "input_url": "tv_stand.png",
  "input_description": "It is stylish"
} 

###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "price": 349
} 

###
DELETE http://localhost:3000/products/3
